services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    extra_hosts:
      - "localhost:172.19.0.6" # Thay bằng IP thực tế của container matching-backend-backend-1
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - matching-backend_matchmaking-network
    command: pnpm run dev

networks:
  matching-backend_matchmaking-network:
    external: true