# Docker Compose file for the matchmaking backend and its dependencies
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
      - redis
      - weaviate
      - embedding
    networks:
      - matchmaking-network

  embedding:
    build:
      context: .
      dockerfile: Dockerfile.embedding
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - redis
      - weaviate
    networks:
      - matchmaking-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: match@123
      MYSQL_DATABASE: matchmaking_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - matchmaking-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - matchmaking-network

  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
    volumes:
      - weaviate-data:/var/lib/weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    networks:
      - matchmaking-network

volumes:
  mysql-data:
  redis-data:
  weaviate-data:

networks:
  matchmaking-network:
    driver: bridge