FROM node:18.20.4
WORKDIR /app
# Cài đặt thư viện cho sharp
RUN apt-get update && apt-get install -y \
    libvips-dev \
    build-essential \
    python3 \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*
COPY apps/backend/package.json ../../pnpm-lock.yaml ./
RUN npm install -g pnpm@10.6.3
RUN pnpm install
# Cài đặt sharp qua PNPM thay vì NPM
RUN pnpm add sharp
COPY apps/backend/src/ ./src/
EXPOSE 8000
CMD ["node", "src/ai/embedServer.js"]